apiVersion: v1
kind: Pod
metadata:
  name: tigergate-debug
  namespace: kube-system
spec:
  hostNetwork: true
  hostPID: true
  serviceAccountName: default
  containers:
    - name: shell
      image: alpine                            # no tag at all
      command: ["sh", "-c", "sleep infinity"]
      securityContext:
        privileged: true
        runAsUser: 0
        procMount: Unmasked
      volumeMounts:
        - name: root
          mountPath: /host
        - name: etc
          mountPath: /etc/host
  volumes:
    - name: root
      hostPath: { path: / }
    - name: etc
      hostPath: { path: /etc }
