apiVersion: v1
kind: Secret
metadata:
  name: tigergate-db
  namespace: default
type: Opaque
data:
  password: UHIwZC1EQi1QYXNzdzByZCE=
stringData:
  jwt-secret: "j0Vm6nOkRs6sULg60pn31p7n0HoD6LEpHG16onyxlnmxa0h0"
  aws-access-key-id: AKIAIOSFODNN7EXAMPLE
  aws-secret-access-key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tigergate-config
  namespace: default
data:
  DB_PASSWORD: "Pr0d-DB-Passw0rd!"      # secret stored in a ConfigMap
  application.properties: |
    spring.datasource.password=Pr0d-DB-Passw0rd!
